### ISSUE TITLE
it does not check for missing arguments for non-mandatory options.

### ISSUE THREAD

**Issue by lasersquad0** [iFuSiiOnzZ/command-line-argument-parser#2]
It would be great to add such check.

**Comment by lasersquad0** [comment]
I was not able to commit to your repository, so I created a fork and implemented required methods. You can take a look.

**Comment by iFuSiiOnzZ** [comment]
It is strange, if the option is optional and has arguments it does the check for mandatory elements. The problem comes when you not add that optional option to the program cli, the parser it will fail as it says that is a option with required arguments and no argument has been provided. So there is bug.

**Comment by lasersquad0** [comment]
I've got your latest source and have this bug fixed.
Also I've added checks and error messages if unknown options are met in command line.
Can you tell me how I can commit my changes into your repository? Is it open for commits?

**Comment by iFuSiiOnzZ** [comment]
I have no idea how it work, all the securities are the github default ones. I don't know if it is because people need to be added to the "Collaborators" repos section or what (added you to it).

Anyway, just pushed some changes. Using pointers to the object stored in memory to avoid duplicate data, so it is more easy to keep track of the number of arguments stored by the option 72e05d8affd3dc2ecf1cb97035a3a2d282098e42.

**Comment by lasersquad0** [comment]
It tells me the following error during push.

Pushing lasersquad
Remote: Permission to iFuSiiOnzZ/command-line-argument-parser.git denied to lasersquad0.
Error encountered while pushing to the remote repository: Git failed with a fatal error.
Git failed with a fatal error.
unable to access 'https://github.com/iFuSiiOnzZ/command-line-argument-parser/': The requested URL returned error: 403

**Comment by iFuSiiOnzZ** [comment]
No idea how this works... on the collaborator section it says `Awaiting lasersquad0’s response`.
https://github.com/iFuSiiOnzZ/command-line-argument-parser/invitations

**Comment by lasersquad0** [comment]
I was finally able to commit to the repository and create pull request.
Please check it out.

**Comment by iFuSiiOnzZ** [comment]
https://github.com/iFuSiiOnzZ/command-line-argument-parser/pull/3
PR merged.
